import React from 'react';
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',notation:'compact',maximumFractionDigits:1}).format(n);const colors=['#2450a4','#008f6a','#e69a20','#7c3aed','#db4b4b'];
export type ChartOpportunity={id:string;account:string;title:string;stage:string;amount:number;probability:number;days:number;risk:string;seller:string;line:string};
export const OpportunityFunnel=({opportunities,onStage}:{opportunities:ChartOpportunity[];onStage:(s:string)=>void})=>{const stages=['Calificado','Levantamiento','Cotización','Negociación','Ganada'];const rows=stages.map((stage,i)=>({stage,i,count:opportunities.filter(x=>x.stage===stage).length,value:opportunities.filter(x=>x.stage===stage).reduce((s,x)=>s+x.amount,0)}));const max=Math.max(...rows.map(x=>x.value),1);return <div className="space-y-3 pt-4">{rows.map(x=><button key={x.stage} onClick={()=>onStage(x.stage)} className="flex w-full items-center gap-3 text-left"><b className="w-24 text-[11px]">{x.stage}</b><span className="h-9 flex-1 rounded-lg bg-theme-muted overflow-hidden"><span className="flex h-full items-center rounded-lg px-3 text-[10px] font-bold text-white" style={{width:`${Math.max(18,x.value/max*100)}%`,background:colors[x.i]}}>{x.count} oportunidades</span></span><b className="w-24 text-right font-mono text-[11px]">{money(x.value)}</b></button>)}</div>};
export const PipelineStageChart=({opportunities,onStage}:{opportunities:ChartOpportunity[];onStage:(s:string)=>void})=>{const stages=['Calificado','Levantamiento','Cotización','Negociación','Ganada'];const rows=stages.map((s,i)=>({s,i,v:opportunities.filter(x=>x.stage===s).reduce((a,x)=>a+x.amount,0)}));const max=Math.max(...rows.map(x=>x.v),1);return <div className="mt-5 flex h-[230px] items-end gap-3 border-b border-theme-subtle px-3">{rows.map(x=><button key={x.s} onClick={()=>onStage(x.s)} className="flex h-full flex-1 flex-col items-center justify-end gap-2 pb-2 text-[10px] font-bold"><span className="w-full shrink-0 rounded-t-lg shadow-sm" style={{height:`${Math.max(8,x.v/max*78)}%`,background:colors[x.i]}}/><span>{x.s}</span><span className="font-mono text-theme-muted">{money(x.v)}</span></button>)}</div>};
export const ForecastChart=()=>{const rows=[['Abr',78,64],['May',82,72],['Jun',76,85],['Jul',90,88],['Ago',86,91],['Sep',44,94]];return <div className="mt-5 flex h-[230px] items-end gap-3 border-b border-theme-subtle px-3">{rows.map(([m,won,forecast]:any)=><div key={m} className="relative flex h-full flex-1 items-end gap-1 pb-7 text-center"><span className="flex-1 shrink-0 rounded-t bg-emerald-600 shadow-sm" style={{height:`${won * .78}%`}}/><span className="flex-1 shrink-0 rounded-t bg-theme-primary shadow-sm" style={{height:`${forecast * .78}%`}}/><small className="absolute bottom-2 left-0 right-0 text-[10px] text-theme-muted">{m}</small></div>)}</div>};
export const LeadOriginChart=({onOrigin}:{onOrigin:(x:string)=>void})=>{const rows=[['Referido',5],['Sitio web',4],['Prospección',4],['Evento / feria',3],['Cliente existente',3]];return <div className="mt-5 grid grid-cols-2 gap-3">{rows.map(([n,v],i)=><button key={String(n)} onClick={()=>onOrigin(String(n))} className="flex items-center gap-2 rounded-xl border border-theme-subtle p-3 text-left text-xs"><span className="h-3 w-3 rounded-full" style={{background:colors[i]}}/><span className="flex-1 font-bold">{n}</span><b>{v}</b></button>)}</div>};
export const ActivityChart=()=>{const rows=[4,6,5,8,7,2,1];return <div className="mt-5 flex h-[230px] items-end gap-3 border-b border-theme-subtle px-3">{rows.map((v,i)=><div key={i} className="flex h-full flex-1 flex-col justify-end pb-2 text-center"><div className="shrink-0 rounded-t bg-theme-primary shadow-sm" style={{height:`${v/8*78}%`}}/><small className="mt-2 block text-[10px] text-theme-muted">{['L','M','M','J','V','S','D'][i]}</small></div>)}</div>};
export const OpportunityBubbleChart=({opportunities,onOpen}:{opportunities:ChartOpportunity[];onOpen:(id:string)=>void})=><div className="grid grid-cols-3 gap-3 pt-5">{opportunities.filter(x=>!['Ganada','Perdida'].includes(x.stage)).slice(0,9).map(x=><button key={x.id} onClick={()=>onOpen(x.id)} className="rounded-full border-2 p-4 text-center text-[10px]" style={{borderColor:x.risk==='Alto'||x.risk==='Crítico'?'#db4b4b':'#2450a4'}}><b>{x.account}</b><span className="block">{x.probability}% · {money(x.amount)}</span></button>)}</div>;
