// @ts-nocheck
import React, { useMemo, useState } from 'react';
import { ArrowLeftRight, CheckCircle2, Download, FileText, Plus, SlidersHorizontal, X } from 'lucide-react';
import { ModalPortal } from '../common/ModalPortal';

const mx=(n:number)=>n.toLocaleString('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0});
const Card=({children,className=''})=><section className={'rounded-2xl border border-theme-subtle bg-theme-surface shadow-2xs '+className}>{children}</section>;
const centersSeed=[
 {id:'CC-101',name:'Producción Offset',owner:'Responsable de producción demo',budget:860000,actual:832000,committed:48000,trend:[72,74,76,80,82,85,89,92,97]},
 {id:'CC-102',name:'Flexografía',owner:'Responsable de línea demo',budget:710000,actual:584000,committed:32000,trend:[55,58,61,65,70,74,77,80,82]},
 {id:'CC-103',name:'Serigrafía y Acabados',owner:'Responsable de acabados demo',budget:360000,actual:244000,committed:18000,trend:[41,46,49,54,57,61,64,66,68]},
 {id:'CC-104',name:'Mantenimiento',owner:'Responsable técnico demo',budget:380000,actual:412000,committed:18400,trend:[52,55,58,60,66,71,79,91,108]},
 {id:'CC-105',name:'Calidad',owner:'Responsable de calidad demo',budget:210000,actual:168000,committed:12600,trend:[48,51,56,59,62,66,70,74,80]},
 {id:'CC-106',name:'Compras',owner:'Responsable de compras demo',budget:190000,actual:126000,committed:9500,trend:[38,41,44,48,52,55,59,63,66]},
 {id:'CC-107',name:'Administración',owner:'Responsable administrativo demo',budget:420000,actual:292000,committed:22800,trend:[42,45,49,53,56,61,64,67,70]},
];
const commitments=[
 ['CMP-2601','OC-RTM-2026-0089','Bio-Pappel · papel bond','Producción Offset',48000,'12 Sep','Autorizado'],['CMP-2602','FP-662190','Avery Dennison · sustratos','Flexografía',32000,'08 Sep','Facturado'],['CMP-2603','OT-MAN-2026-014','Servicio compresor Kaeser','Mantenimiento',18400,'10 Sep','Pendiente'],['CMP-2604','OC-RTM-2026-0102','Barniz y consumibles','Serigrafía y Acabados',18000,'16 Sep','Autorizado'],['CMP-2605','CX-2026-091','Calibración de instrumentos','Calidad',12600,'18 Sep','Pendiente'],['CMP-2606','OC-RTM-2026-0107','Fletes de entrada','Compras',9500,'11 Sep','Aplicado'],['CMP-2607','FP-778120','Renta y servicios planta','Administración',22800,'15 Sep','Facturado'],['CMP-2608','OC-RTM-2026-0111','Rodillos y refacciones','Producción Offset',16400,'21 Sep','Pendiente'],['CMP-2609','REQ-2026-028','Tinta flexográfica','Flexografía',13700,'19 Sep','Autorizado'],['CMP-2610','NOM-SEM-2026-36','Nómina indirecta','Administración',19600,'13 Sep','Aplicado'],
].map(([id,folio,concept,center,amount,date,status])=>({id,folio,concept,center,amount,date,status}));
const months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep'];
const status=(c:any)=>{const p=(c.actual+c.committed)/Math.max(c.budget,1)*100;return p>100?['Excedido','bg-rose-500','text-rose-700']:p>=85?['Atención','bg-amber-500','text-amber-700']:['Dentro de presupuesto','bg-emerald-500','text-emerald-700'];};

export const BudgetWorkspace=({toast}:{toast:(x:string)=>void})=>{
 const [tab,setTab]=useState('Resumen'),[centers,setCenters]=useState(centersSeed),[period,setPeriod]=useState('Septiembre 2026'),[filter,setFilter]=useState('Todos'),[detail,setDetail]=useState<any>(null),[modal,setModal]=useState('');
 const visible=centers.filter(c=>filter==='Todos'||c.name===filter); const total=(key:string)=>visible.reduce((s,c)=>s+c[key],0); const approved=total('budget'),actual=total('actual'),committed=total('committed'),available=approved-actual-committed;
 const update=(id:string,patch:any)=>setCenters(list=>list.map(c=>c.id===id?{...c,...patch}:c));
 const open=(c:any,mode='detail')=>{setDetail(c);setModal(mode)};
 return <div className="space-y-4">
  <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex flex-wrap gap-1 rounded-xl bg-theme-muted/60 p-1">{['Resumen','Presupuestos','Presupuesto vs Real','Centros de Costo','Compromisos'].map(x=><button key={x} onClick={()=>setTab(x)} className={'rounded-lg px-3 py-2 text-xs font-bold '+(tab===x?'bg-theme-surface shadow-2xs text-theme-main':'text-theme-muted')}>{x}</button>)}</div><div className="flex flex-wrap gap-2"><select value={period} onChange={e=>setPeriod(e.target.value)} className="rounded-xl border border-theme-subtle bg-theme-surface px-3 py-2 text-xs"><option>Septiembre 2026</option><option>Agosto 2026</option><option>Julio 2026</option><option>Acumulado 2026</option></select><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-theme-subtle bg-theme-surface px-3 py-2 text-xs"><option>Todos</option>{centers.map(c=><option key={c.id}>{c.name}</option>)}</select><button onClick={()=>setModal('new')} className="rounded-xl bg-theme-primary px-3 py-2 text-xs font-bold text-white"><Plus className="mr-1 inline h-3.5 w-3.5"/>Nuevo presupuesto</button><button onClick={()=>toast('Exportación presupuestal preparada · Demo')} className="rounded-xl border border-theme-subtle px-3 py-2 text-xs font-bold"><Download className="mr-1 inline h-3.5 w-3.5"/>Exportar</button></div></div>
  <div className="grid grid-cols-2 xl:grid-cols-6 gap-3">{[['Presupuesto anual',approved],['Ejercido',actual],['Comprometido',committed],['Disponible',available],['Variación vs plan',approved-actual],['% ejecución',Math.round(actual/Math.max(approved,1)*100)+'%']].map(([l,v])=><Card key={String(l)}><div className="p-4"><small className="text-[10px] font-bold uppercase text-theme-muted">{l}</small><b className="mt-2 block font-mono text-lg">{typeof v==='number'?mx(v):v}</b><small className="text-theme-muted">{period} · demo</small></div></Card>)}</div>
  {tab==='Resumen'&&<><div className="grid xl:grid-cols-[1.25fr_.75fr] gap-4"><MonthlyChart centers={visible}/><Attention centers={visible} open={open}/></div><ControlTable centers={visible} open={open}/></>}
  {tab==='Presupuestos'&&<><div className="flex justify-end"><button onClick={()=>setModal('transfer')} className="rounded-xl border border-theme-subtle px-3 py-2 text-xs font-bold"><ArrowLeftRight className="mr-1 inline h-3.5 w-3.5"/>Transferir presupuesto</button></div><BudgetTable centers={visible} open={open} onClose={c=>open(c,'close')}/></>}
  {tab==='Presupuesto vs Real'&&<VarianceView centers={visible} open={open}/>} {tab==='Centros de Costo'&&<Centers centers={visible} open={open}/>} {tab==='Compromisos'&&<Commitments rows={commitments.filter(x=>filter==='Todos'||x.center===filter)} open={open} centers={centers}/>}
  {modal==='detail'&&detail&&<CenterDetail center={centers.find(c=>c.id===detail.id)||detail} close={()=>setModal('')} openAction={(m:string)=>setModal(m)} toast={toast}/>} {modal==='new'&&<NewBudget close={()=>setModal('')} add={c=>{setCenters(x=>[...x,c]);setModal('');toast('Presupuesto demo creado y disponible en control por centro.')}}/>} {modal==='adjust'&&detail&&<Adjust center={centers.find(c=>c.id===detail.id)} close={()=>setModal('')} save={n=>{update(detail.id,{budget:n});setModal('');toast('Ajuste presupuestal registrado · Demo')}}/>} {modal==='transfer'&&<Transfer centers={centers} close={()=>setModal('')} save={(from,to,amount)=>{update(from,{budget:centers.find(x=>x.id===from).budget-amount});update(to,{budget:centers.find(x=>x.id===to).budget+amount});setModal('');toast('Transferencia presupuestal registrada · Demo')}}/>} {modal==='close'&&detail&&<ClosePeriod center={centers.find(c=>c.id===detail.id)} close={()=>setModal('')} done={()=>{setModal('');toast('Periodo marcado como cerrado · Demostración visual')}}/>}
 </div>;
};

const MonthlyChart=({centers})=>{const budget=centers.reduce((s,c)=>s+c.budget,0)/9;const real=months.map((_,i)=>centers.reduce((s,c)=>s+c.budget*c.trend[i]/900,0));const commit=months.map((_,i)=>centers.reduce((s,c)=>s+c.committed*(i+1)/45,0));const max=Math.max(budget,...real.map((x,i)=>x+commit[i]));return <Card><div className="p-5"><div className="flex justify-between"><div><b>Presupuesto vs Real · mensual</b><p className="mt-1 text-xs text-theme-muted">Aprobado, ejercido y comprometido · datos demo.</p></div><span className="text-xs font-bold text-theme-primary">{centers.length} centros</span></div><div className="mt-5 flex h-56 items-end gap-2 border-b border-theme-subtle px-3">{months.map((m,i)=><div key={m} className="flex h-full flex-1 items-end justify-center gap-1 pb-6 relative"><span title={`${m} · Presupuesto ${mx(budget)}`} className="w-1/3 rounded-t bg-theme-muted" style={{height:`${budget/max*78}%`}}/><span title={`${m} · Ejercido ${mx(real[i])}`} className="w-1/3 rounded-t bg-theme-primary shadow-sm" style={{height:`${real[i]/max*78}%`}}/><span title={`${m} · Comprometido ${mx(commit[i])}`} className="w-1/3 rounded-t bg-amber-400" style={{height:`${commit[i]/max*78}%`}}/><small className="absolute bottom-1 text-[10px] text-theme-muted">{m}</small></div>)}</div><div className="mt-3 flex flex-wrap gap-4 text-[10px] text-theme-muted"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-theme-muted"/>Presupuesto</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-theme-primary"/>Ejercido</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-amber-400"/>Comprometido</span></div></div></Card>};
const Attention=({centers,open})=><Card><div className="p-5 border-b border-theme-subtle"><b>Atención presupuestal</b><p className="mt-1 text-xs text-theme-muted">Centros con impacto sobre la operación.</p></div>{[...centers].sort((a,b)=>(b.actual+b.committed)/b.budget-(a.actual+a.committed)/a.budget).slice(0,5).map(c=>{const pct=Math.round((c.actual+c.committed)/c.budget*100),s=status(c);return <button onClick={()=>open(c)} key={c.id} className="w-full border-b border-theme-subtle p-4 text-left hover:bg-theme-muted/30"><div className="flex justify-between text-xs"><b>{c.name}</b><span className={s[2]+' font-bold'}>{pct}% · {s[0]}</span></div><div className="mt-2 h-1.5 rounded-full bg-theme-muted"><span className={'block h-full rounded-full '+s[1]} style={{width:`${Math.min(pct,100)}%`}}/></div><small className="mt-1 block text-theme-muted">{mx(c.actual)} real · {mx(c.committed)} reservado</small></button>})}</Card>;
const ControlTable=({centers,open})=><Card><div className="flex justify-between border-b border-theme-subtle p-5"><div><b>Control presupuestal por centro de costo</b><p className="mt-1 text-xs text-theme-muted">Haz clic para abrir partidas, documentos y movimientos.</p></div><span className="text-xs text-theme-muted">{centers.length} centros</span></div><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-xs"><thead className="bg-theme-muted/50 text-[10px] uppercase text-theme-muted"><tr>{['Centro','Responsable','Aprobado','Ejercido','Comprometido','Disponible','% ejecución','Estado',''].map(x=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{centers.map((c,i)=>{const p=Math.round((c.actual+c.committed)/c.budget*100),s=status(c);return <tr key={c.id} className={'border-t border-theme-subtle hover:bg-theme-muted/30 '+(i%2?'bg-theme-muted/10':'')}><td className="p-4"><b>{c.name}</b><small className="block font-mono text-theme-muted">{c.id}</small></td><td className="p-4">{c.owner}</td><td className="p-4 font-mono">{mx(c.budget)}</td><td className="p-4 font-mono">{mx(c.actual)}</td><td className="p-4 font-mono">{mx(c.committed)}</td><td className={'p-4 font-mono font-bold '+(c.budget-c.actual-c.committed<0?'text-rose-700':'')}>{mx(c.budget-c.actual-c.committed)}</td><td className="p-4 min-w-[130px]"><div className="flex items-center gap-2"><span className="h-2 flex-1 rounded-full bg-theme-muted"><i className={'block h-full rounded-full '+s[1]} style={{width:`${Math.min(p,100)}%`}}/></span><b>{p}%</b></div></td><td className="p-4"><span className={'rounded-full border px-2 py-1 text-[10px] font-bold '+s[2]}>{s[0]}</span></td><td className="p-4"><button onClick={()=>open(c)} className="font-bold text-theme-primary">Ver detalle</button></td></tr>})}</tbody></table></div></Card>;
const BudgetTable=({centers,open,onClose})=><Card><div className="border-b border-theme-subtle p-5"><b>Presupuestos operativos</b><p className="mt-1 text-xs text-theme-muted">Control por centro, periodo, variación y acciones locales.</p></div><div className="overflow-x-auto"><table className="min-w-[1180px] w-full text-xs"><thead className="bg-theme-muted/50 text-[10px] uppercase text-theme-muted"><tr>{['Folio / presupuesto','Centro','Responsable','Periodo','Aprobado','Ejercido','Comprometido','Disponible','Variación','%','Estado','Acciones'].map(x=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{centers.map(c=>{const available=c.budget-c.actual-c.committed,p=Math.round(c.actual/c.budget*100),s=status(c);return <tr key={c.id} className="border-t border-theme-subtle"><td className="p-3"><b>PRE-2026-{c.id.slice(-3)}</b><small className="block text-theme-muted">Presupuesto operativo</small></td><td className="p-3">{c.name}</td><td className="p-3">{c.owner}</td><td className="p-3">Septiembre 2026</td><td className="p-3 font-mono">{mx(c.budget)}</td><td className="p-3 font-mono">{mx(c.actual)}</td><td className="p-3 font-mono">{mx(c.committed)}</td><td className="p-3 font-mono">{mx(available)}</td><td className={'p-3 font-mono '+(c.budget-c.actual<0?'text-rose-700':'text-emerald-700')}>{mx(c.budget-c.actual)}</td><td className="p-3">{p}%</td><td className="p-3"><span className={'rounded-full px-2 py-1 text-[10px] font-bold '+s[2]}>{s[0]}</span></td><td className="p-3 whitespace-nowrap"><button onClick={()=>open(c)} className="mr-2 font-bold text-theme-primary">Detalle</button><button onClick={()=>open(c,'adjust')} className="mr-2 font-bold text-theme-primary">Ajustar</button><button onClick={()=>onClose(c)} className="font-bold text-theme-muted">Cerrar</button></td></tr>})}</tbody></table></div></Card>;
const VarianceView=({centers,open})=><div className="space-y-4"><div className="grid xl:grid-cols-2 gap-4"><MonthlyChart centers={centers}/><Card><div className="p-5"><b>Top desviaciones</b><p className="mt-1 text-xs text-theme-muted">Variación real contra presupuesto aprobado.</p><div className="mt-5 space-y-4">{[...centers].sort((a,b)=>(b.actual-b.budget)-(a.actual-a.budget)).map(c=>{const v=c.actual-c.budget;return <button onClick={()=>open(c)} key={c.id} className="w-full text-left"><div className="flex justify-between text-xs"><b>{c.name}</b><b className={v>0?'text-rose-700':'text-emerald-700'}>{v>0?'+':''}{mx(v)} · {Math.round(v/c.budget*100)}%</b></div><div className="mt-2 h-2 rounded-full bg-theme-muted"><span className={'block h-full rounded-full '+(v>0?'bg-rose-500':'bg-emerald-500')} style={{width:`${Math.min(100,Math.abs(v)/c.budget*250+20)}%`}}/></div></button>})}</div></div></Card></div><ControlTable centers={centers} open={open}/></div>;
const Centers=({centers,open})=><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{centers.map(c=>{const p=Math.round((c.actual+c.committed)/c.budget*100),s=status(c);return <Card key={c.id}><button onClick={()=>open(c)} className="w-full p-5 text-left hover:bg-theme-muted/20"><div className="flex justify-between"><span><b>{c.name}</b><small className="block mt-1 font-mono text-theme-muted">{c.id}</small></span><span className={'text-xs font-bold '+s[2]}>{p}%</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><span>Presupuesto<b className="block font-mono">{mx(c.budget)}</b></span><span>Disponible<b className="block font-mono">{mx(c.budget-c.actual-c.committed)}</b></span><span>Ejercido<b className="block font-mono">{mx(c.actual)}</b></span><span>Comprometido<b className="block font-mono">{mx(c.committed)}</b></span></div><div className="mt-4 h-2 rounded-full bg-theme-muted"><span className={'block h-full rounded-full '+s[1]} style={{width:`${Math.min(p,100)}%`}}/></div><small className="mt-3 block text-theme-muted">{c.owner} · Abrir centro</small></button></Card>})}</div>;
const Commitments=({rows,open,centers})=><Card><div className="flex justify-between border-b border-theme-subtle p-5"><div><b>Compromisos presupuestales</b><p className="mt-1 text-xs text-theme-muted">Monto reservado antes de convertirse en gasto ejercido.</p></div><span className="text-xs text-theme-muted">{rows.length} documentos</span></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-xs"><thead className="bg-theme-muted/50 text-[10px] uppercase text-theme-muted"><tr>{['Documento origen','Proveedor / concepto','Centro de costo','Monto','Fecha esperada','Estado','Impacto'].map(x=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-theme-subtle hover:bg-theme-muted/30"><td className="p-3"><button onClick={()=>open(centers.find(c=>c.name===r.center))} className="font-mono font-bold text-theme-primary">{r.folio}</button><small className="block text-theme-muted">{r.id}</small></td><td className="p-3">{r.concept}</td><td className="p-3">{r.center}</td><td className="p-3 font-mono">{mx(r.amount)}</td><td className="p-3">{r.date}</td><td className="p-3"><span className="rounded-full border border-theme-subtle px-2 py-1 text-[10px] font-bold">{r.status}</span></td><td className="p-3 text-theme-muted">Reserva disponible</td></tr>)}</tbody></table></div></Card>;
const CenterDetail=({center,close,openAction,toast})=>{const [view,setView]=useState('Resumen');const parts=[['Materiales',center.budget*.42,center.actual*.44,center.committed*.45],['Servicios',center.budget*.18,center.actual*.16,center.committed*.20],['Mantenimiento',center.budget*.14,center.actual*.17,center.committed*.12],['Fletes',center.budget*.08,center.actual*.07,center.committed*.08],['Nómina indirecta',center.budget*.10,center.actual*.09,center.committed*.10],['Gastos administrativos',center.budget*.08,center.actual*.07,center.committed*.05]];const docs=commitments.filter(x=>x.center===center.name);return <ModalPortal onClose={close}><div className="w-full max-w-5xl max-h-[90vh] overflow-y-auto rounded-3xl bg-theme-surface shadow-2xl"><div className="sticky top-0 z-10 flex justify-between border-b border-theme-subtle bg-theme-surface p-6"><div><p className="text-[10px] font-black tracking-widest text-theme-primary">CENTRO DE COSTO · {center.id}</p><h2 className="text-xl font-black">{center.name}</h2><p className="text-xs text-theme-muted">{center.owner} · Datos demostrativos</p></div><button onClick={close}><X/></button></div><div className="flex flex-wrap gap-1 border-b border-theme-subtle p-4">{['Resumen','Partidas','Compromisos','Movimientos','Historial'].map(x=><button onClick={()=>setView(x)} key={x} className={'rounded-lg px-3 py-2 text-xs font-bold '+(view===x?'bg-theme-primary text-white':'bg-theme-muted text-theme-muted')}>{x}</button>)}</div><div className="p-6">{view==='Resumen'&&<><div className="grid grid-cols-2 xl:grid-cols-5 gap-3">{[['Aprobado',center.budget],['Ejercido',center.actual],['Comprometido',center.committed],['Disponible',center.budget-center.actual-center.committed],['Variación',center.budget-center.actual]].map(x=><div key={x[0]} className="rounded-xl border border-theme-subtle p-3 text-xs"><small className="text-theme-muted">{x[0]}</small><b className="block font-mono">{mx(x[1])}</b></div>)}</div><div className="mt-5 flex gap-2"><button onClick={()=>openAction('adjust')} className="rounded-xl bg-theme-primary px-3 py-2 text-xs font-bold text-white">Ajustar presupuesto</button><button onClick={()=>toast('Documentos relacionados preparados · Demo')} className="rounded-xl border border-theme-subtle px-3 py-2 text-xs font-bold">Ver trazabilidad</button></div></>}{view==='Partidas'&&<PartTable rows={parts}/>} {view==='Compromisos'&&<Commitments rows={docs} open={()=>{}} centers={[center]}/>} {view==='Movimientos'&&<Timeline rows={['08 Sep · Factura proveedor aplicada','06 Sep · Compromiso OC reservado','02 Sep · Gasto ejercido','28 Ago · Ajuste de periodo']}/>} {view==='Historial'&&<Timeline rows={['01 Ene · Presupuesto creado','04 Jul · Transferencia recibida','28 Ago · Ajuste registrado','Pendiente · Cierre de septiembre']}/>}</div></div></ModalPortal>};
const PartTable=({rows})=><table className="w-full text-xs"><thead className="bg-theme-muted"><tr>{['Partida','Presupuesto','Real','Comprometido','Disponible','Estado'].map(x=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(x=>{const d=x[1]-x[2]-x[3];return <tr className="border-b border-theme-subtle" key={x[0]}><td className="p-3 font-bold">{x[0]}</td><td className="p-3 font-mono">{mx(x[1])}</td><td className="p-3 font-mono">{mx(x[2])}</td><td className="p-3 font-mono">{mx(x[3])}</td><td className="p-3 font-mono">{mx(d)}</td><td className="p-3">{d<0?'Excedido':'En control'}</td></tr>})}</tbody></table>;
const Timeline=({rows})=><div className="space-y-3">{rows.map((x,i)=><div className="flex gap-3 text-xs" key={x}><span className="mt-1.5 h-2.5 w-2.5 rounded-full bg-theme-primary"/><span><b>{x}</b><small className="block text-theme-muted">Registro demostrativo de trazabilidad presupuestal · #{i+1}</small></span></div>)}</div>;
const NewBudget=({close,add})=>{const [name,setName]=useState(''),[amount,setAmount]=useState('250000');return <ModalPortal onClose={close}><div className="w-full max-w-lg rounded-3xl bg-theme-surface p-6"><div className="flex justify-between"><div><p className="text-[10px] font-black text-theme-primary">NUEVO PRESUPUESTO · DEMO</p><h2 className="text-lg font-black">Crear presupuesto operativo</h2></div><button onClick={close}><X/></button></div><div className="mt-5 space-y-3 text-xs"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre / concepto" className="w-full rounded-xl border border-theme-subtle p-3"/><select className="w-full rounded-xl border border-theme-subtle p-3"><option>Septiembre 2026</option><option>Acumulado 2026</option></select><input value={amount} onChange={e=>setAmount(e.target.value)} type="number" className="w-full rounded-xl border border-theme-subtle p-3"/><textarea placeholder="Notas demo" className="w-full rounded-xl border border-theme-subtle p-3"/></div><button onClick={()=>add({id:'CC-'+(108+Date.now()%90),name:name||'Centro operativo demo',owner:'Responsable demo',budget:Number(amount)||0,actual:0,committed:0,trend:[0,0,0,0,0,0,0,0,0]})} className="mt-5 w-full rounded-xl bg-theme-primary p-3 text-xs font-bold text-white">Crear presupuesto</button></div></ModalPortal>};
const Adjust=({center,close,save})=>{const [delta,setDelta]=useState('0'),[reason,setReason]=useState('');return <ModalPortal onClose={close}><div className="w-full max-w-lg rounded-3xl bg-theme-surface p-6"><div className="flex justify-between"><h2 className="font-black">Ajustar · {center.name}</h2><button onClick={close}><X/></button></div><p className="mt-3 text-xs text-theme-muted">Monto actual: <b className="font-mono">{mx(center.budget)}</b></p><input value={delta} onChange={e=>setDelta(e.target.value)} type="number" className="mt-4 w-full rounded-xl border border-theme-subtle p-3 text-xs" placeholder="Ajuste + / -"/><textarea value={reason} onChange={e=>setReason(e.target.value)} className="mt-3 w-full rounded-xl border border-theme-subtle p-3 text-xs" placeholder="Motivo demo"/><button onClick={()=>save(center.budget+Number(delta||0))} className="mt-4 w-full rounded-xl bg-theme-primary p-3 text-xs font-bold text-white">Registrar ajuste · Nuevo total {mx(center.budget+Number(delta||0))}</button></div></ModalPortal>};
const Transfer=({centers,close,save})=>{const [from,setFrom]=useState(centers[0].id),[to,setTo]=useState(centers[1].id),[amount,setAmount]=useState('10000');return <ModalPortal onClose={close}><div className="w-full max-w-lg rounded-3xl bg-theme-surface p-6"><div className="flex justify-between"><h2 className="font-black">Transferir presupuesto</h2><button onClick={close}><X/></button></div><div className="mt-5 grid gap-3 text-xs"><select value={from} onChange={e=>setFrom(e.target.value)} className="rounded-xl border border-theme-subtle p-3">{centers.map(c=><option value={c.id} key={c.id}>Origen · {c.name}</option>)}</select><select value={to} onChange={e=>setTo(e.target.value)} className="rounded-xl border border-theme-subtle p-3">{centers.filter(c=>c.id!==from).map(c=><option value={c.id} key={c.id}>Destino · {c.name}</option>)}</select><input value={amount} onChange={e=>setAmount(e.target.value)} type="number" className="rounded-xl border border-theme-subtle p-3"/></div><button onClick={()=>from!==to&&save(from,to,Number(amount)||0)} className="mt-5 w-full rounded-xl bg-theme-primary p-3 text-xs font-bold text-white">Registrar transferencia</button></div></ModalPortal>};
const ClosePeriod=({center,close,done})=><ModalPortal onClose={close}><div className="w-full max-w-lg rounded-3xl bg-theme-surface p-6"><div className="flex justify-between"><h2 className="font-black">Cerrar periodo · Demo</h2><button onClick={close}><X/></button></div><p className="mt-4 text-xs text-theme-muted">Se registrará el cierre visual de {center.name}; no bloquea contabilidad ni crea pólizas.</p><div className="mt-4 grid grid-cols-3 gap-2 text-xs">{[['Aprobado',center.budget],['Ejercido',center.actual],['Comprometido',center.committed]].map(x=><span key={x[0]} className="rounded-xl border border-theme-subtle p-3"><small>{x[0]}</small><b className="block font-mono">{mx(x[1])}</b></span>)}</div><button onClick={done} className="mt-5 w-full rounded-xl bg-theme-primary p-3 text-xs font-bold text-white"><CheckCircle2 className="mr-1 inline h-4 w-4"/>Confirmar cierre demostrativo</button></div></ModalPortal>;
