import React, { useMemo, useState } from 'react';
import { AccountReceivable, SalesInvoice, SupplierInvoice } from '../../data/mockFinanzasData';
import { BarChart3, BookOpen, Building2, CalendarClock, CheckCircle2, CircleDollarSign, FileBarChart, Landmark, WalletCards } from 'lucide-react';
type Props={salesInvoices:SalesInvoice[];cxc:AccountReceivable[];cxp:SupplierInvoice[]};
const mx=(n:number)=>'$'+n.toLocaleString('es-MX',{minimumFractionDigits:2});
const Card=({label,value,note,tone='text-theme-main'}:{label:string;value:string;note:string;tone?:string})=><div className="p-4 rounded-2xl bg-theme-surface border border-theme-subtle"><p className="text-[10px] font-bold uppercase text-theme-muted">{label}</p><p className={'mt-2 font-mono text-xl font-black '+tone}>{value}</p><p className="mt-1 text-[11px] text-theme-muted">{note}</p></div>;
export const FinanceHub:React.FC<Props>=({salesInvoices,cxc,cxp})=>{const [tab,setTab]=useState<'dashboard'|'treasury'|'accounting'|'reports'>('dashboard');const [notice,setNotice]=useState('');
const t=useMemo(()=>({sales:salesInvoices.reduce((s,i)=>s+i.total,0),collected:cxc.reduce((s,i)=>s+i.totalPagado,0),cxc:cxc.reduce((s,i)=>s+i.saldoPendiente,0),overdue:cxc.filter(i=>i.status==='vencida').reduce((s,i)=>s+i.saldoPendiente,0),cxp:cxp.reduce((s,i)=>s+i.saldoPendiente,0),upcoming:cxp.filter(i=>i.estadoPago==='programada'||i.estadoPago==='parcial').reduce((s,i)=>s+i.saldoPendiente,0)}),[salesInvoices,cxc,cxp]);const cash=486200;const profit=t.sales-t.cxp*0.42-128460;const tabs=[['dashboard','Dashboard'],['treasury','Tesorería'],['accounting','Contabilidad'],['reports','Reportes financieros']] as const;
return <div className="space-y-5"><div><h1 className="text-2xl font-black">Finanzas</h1><p className="text-xs text-theme-muted mt-1">Visibilidad ejecutiva, caja, contabilidad y reportes demostrativos.</p></div><div className="flex flex-wrap gap-1 border-b border-theme-subtle">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={'px-4 py-3 text-xs font-bold border-b-2 cursor-pointer '+(tab===id?'border-theme-primary text-theme-primary':'border-transparent text-theme-muted')}>{label}</button>)}</div>{notice&&<div className="p-3 text-xs bg-emerald-50 border border-emerald-200 text-emerald-800 rounded-xl">{notice}</div>}
{tab==='dashboard'&&<div className="space-y-4"><div className="grid grid-cols-2 xl:grid-cols-4 gap-3"><Card label="Ventas facturadas" value={mx(t.sales)} note="Mes actual" /><Card label="Cobranza del mes" value={mx(t.collected)} note="Pagos aplicados" tone="text-emerald-700"/><Card label="CxC pendiente" value={mx(t.cxc)} note={'Vencida: '+mx(t.overdue)} tone="text-amber-700"/><Card label="CxP pendiente" value={mx(t.cxp)} note="Proveedores y gastos" tone="text-rose-700"/><Card label="Pagos próximos 7 días" value={mx(t.upcoming)} note="Programados" /><Card label="Posición de efectivo" value={mx(cash)} note="Saldo disponible demo" tone="text-blue-700"/><Card label="Resultado operativo" value={mx(profit)} note="Estimación demostrativa" tone="text-emerald-700"/></div><div className="grid xl:grid-cols-2 gap-4"><Panel title="Flujo de caja · 30 días"><Rows rows={[['Entradas esperadas',mx(t.cxc),'text-emerald-700'],['Salidas programadas',mx(t.upcoming),'text-rose-700'],['Flujo proyectado',mx(t.cxc-t.upcoming),'text-theme-primary']]}/></Panel><Panel title="Próximos compromisos"><Rows rows={[['Cobro cliente pendiente',mx(t.overdue),'text-amber-700'],['Pago proveedor programado',mx(t.upcoming),'text-rose-700'],['Nómina semanal',mx(128460),'text-theme-main'],['Servicios recurrentes',mx(93440),'text-theme-main']]}/></Panel></div></div>}
{tab==='treasury'&&<div className="space-y-4"><div className="grid md:grid-cols-3 gap-3">{[['Cuenta Operativa MXN — Demo',cash,96200],['Cuenta Nómina MXN — Demo',184500,128460],['Cuenta USD — Demo',64200,0]].map(([n,s,c])=><div key={String(n)} className="p-4 rounded-2xl border border-theme-subtle bg-theme-surface"><p className="font-bold text-xs">{n}</p><p className="font-mono font-black text-lg mt-2">{mx(Number(s))}</p><p className="text-[11px] text-theme-muted">Comprometido: {mx(Number(c))} · Proyectado: {mx(Number(s)-Number(c))}</p></div>)}</div><Panel title="Pagos programados y movimientos"><Rows rows={[['07 Sep · Cobro CxC · FAC-RTM-2026-0045',mx(30000),'text-emerald-700'],['08 Sep · Pago CxP · FP-662190',mx(50800),'text-rose-700'],['14 Sep · Nómina semanal',mx(128460),'text-rose-700'],['15 Sep · Servicios recurrentes',mx(39800),'text-rose-700']]}/></Panel><Panel title="Conciliación bancaria"><p className="text-xs text-amber-800 bg-amber-50 border border-amber-200 p-3 rounded-xl">Conciliación bancaria simulada — Demo</p><div className="flex gap-2 mt-3"><button onClick={()=>setNotice('Movimiento conciliado correctamente · Demo')} className="px-3 py-2 text-xs font-bold bg-theme-primary text-white rounded-xl">Conciliar</button><button onClick={()=>setNotice('Diferencia marcada para revisión · Demo')} className="px-3 py-2 text-xs font-bold border rounded-xl">Marcar diferencia</button></div></Panel></div>}
{tab==='accounting'&&<div className="space-y-4"><Panel title="Catálogo de cuentas · Demo"><Rows rows={[['1101','Bancos','Activo'],['1102','Clientes','Activo'],['2101','Proveedores','Pasivo'],['2103','Nómina por pagar','Pasivo'],['4101','Ventas nacionales','Ingresos'],['5101','Costo de ventas','Costos'],['6104','Mantenimiento','Gastos']]}/></Panel><Panel title="Pólizas generadas desde operaciones"><Rows rows={[['PV-2026-048','Factura de venta timbrada','Debe '+mx(172260)+' · Haber '+mx(172260)],['PC-2026-045','Cobro cliente','Debe '+mx(30000)+' · Haber '+mx(30000)],['PE-2026-084','Factura proveedor','Debe '+mx(109504)+' · Haber '+mx(109504)],['PN-2026-036','Nómina semanal','Debe '+mx(128460)+' · Haber '+mx(128460)] ]}/></Panel><Panel title="Balanza de comprobación"><Rows rows={[['Bancos',mx(486200),mx(128460)],['Clientes',mx(t.cxc),mx(t.sales)],['Proveedores',mx(t.cxp),mx(t.cxp)],['Ventas nacionales',mx(0),mx(t.sales)] ]}/></Panel></div>}
{tab==='reports'&&<div className="space-y-4"><div className="grid xl:grid-cols-2 gap-4"><Panel title="Estado de Resultados · Sep 2026"><Rows rows={[['Ventas netas',mx(t.sales),'text-emerald-700'],['Costo de ventas',mx(t.cxp*.42),'text-rose-700'],['Utilidad bruta',mx(t.sales-t.cxp*.42),'text-theme-main'],['Gastos operativos',mx(128460),'text-rose-700'],['Utilidad operativa',mx(profit),'text-theme-primary']]}/></Panel><Panel title="Balance General · Demo"><Rows rows={[['Activo circulante',mx(cash+t.cxc),'text-theme-main'],['Activo no circulante',mx(1200000),'text-theme-main'],['Pasivo',mx(t.cxp+220000),'text-rose-700'],['Capital',mx(cash+t.cxc+1200000-t.cxp-220000),'text-theme-primary']]}/></Panel></div><Panel title="Reportes contables"><div className="flex flex-wrap gap-2">{['Balanza de comprobación','Auxiliar de cuenta','Libro diario','Libro mayor','Flujo de efectivo'].map(x=><button key={x} onClick={()=>setNotice(x+' preparado correctamente · Función demostrativa')} className="px-3 py-2 text-xs font-bold border border-theme-subtle rounded-xl">{x}</button>)}</div></Panel></div>}</div>};
const Panel=({title,children}:{title:string;children:React.ReactNode})=><section className="p-4 rounded-2xl bg-theme-surface border border-theme-subtle"><h2 className="font-black text-sm mb-3">{title}</h2>{children}</section>;
const Rows=({rows}:{rows:(string|undefined)[][]})=><div className="divide-y divide-theme-subtle">{rows.map((r,i)=><div key={i} className="py-2 flex justify-between gap-3 text-xs"><span className="font-medium">{r[0]}{r[2]&&r.length===3?<small className="block text-theme-muted">{r[2]}</small>:null}</span><span className={'font-mono font-bold '+(r[2]?.startsWith('text-')?r[2]:'')}>{r[1]}</span></div>)}</div>;
