import React, { useMemo, useState } from 'react';
import { Search } from 'lucide-react';
import { ProductionArea, ProductionOrder } from '../../data/mockProduccionData';
import { ProductionCard, ProgressBar, StatusBadge } from './productionUi';

interface Props { orders: ProductionOrder[]; onOpenOrder: (order: ProductionOrder) => void; compact?: boolean; }
export const OrdenesProduccion: React.FC<Props> = ({ orders, onOpenOrder, compact = false }) => {
  const [query, setQuery] = useState(''); const [area, setArea] = useState<'Todas' | ProductionArea>('Todas');
  const rows = useMemo(() => orders.filter(order => (area === 'Todas' || order.area === area) && `${order.folio} ${order.cliente} ${order.partNumber}`.toLowerCase().includes(query.toLowerCase())), [area, orders, query]);
  return <ProductionCard><div className="flex flex-wrap items-center justify-between gap-3 border-b border-theme-subtle p-5"><div><b>Órdenes de producción</b><p className="mt-1 text-xs text-theme-muted">Pedido, capacidad, reserva de insumos y avance de piso.</p></div>{!compact && <div className="flex gap-2"><label className="relative"><Search className="absolute left-3 top-2.5 h-3.5 w-3.5 text-theme-muted" /><input value={query} onChange={event => setQuery(event.target.value)} className="w-48 rounded-xl border border-theme-subtle bg-theme-surface py-2 pl-8 pr-3 text-xs" placeholder="Buscar OP o cliente" /></label><select value={area} onChange={event => setArea(event.target.value as 'Todas' | ProductionArea)} className="rounded-xl border border-theme-subtle bg-theme-surface px-2 text-xs"><option>Todas</option><option>Offset</option><option>Flexografía</option><option>Acabados</option></select></div>}</div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-xs"><thead className="bg-theme-muted/50 text-[10px] uppercase text-theme-muted"><tr>{['OP','Pedido','Cliente','Parte / revisión','Área','Compromiso','Estado','Avance',''].map(label => <th className="p-3 text-left" key={label}>{label}</th>)}</tr></thead><tbody>{rows.slice(0, compact ? 7 : rows.length).map(order => <tr className="border-t border-theme-subtle hover:bg-theme-muted/30" key={order.id}><td className="p-3 font-mono font-bold">{order.folio}</td><td className="p-3 font-mono">{order.pedido}</td><td className="p-3 font-bold">{order.cliente}</td><td className="p-3">{order.partNumber}<small className="block text-theme-muted">{order.revision}</small></td><td className="p-3">{order.area}</td><td className="p-3">{order.due}</td><td className="p-3"><StatusBadge status={order.status} /></td><td className="min-w-36 p-3"><ProgressBar value={order.progress} /><small className="mt-1 block text-theme-muted">{order.progress}% · {order.good.toLocaleString('es-MX')} buenas</small></td><td className="p-3"><button onClick={() => onOpenOrder(order)} className="font-bold text-theme-primary">Abrir OP</button></td></tr>)}</tbody></table></div></ProductionCard>;
};
