import React, { useState } from 'react';
import { AlertTriangle, CalendarDays, ChevronRight } from 'lucide-react';
import { PRODUCTION_MACHINES, ProductionArea, ProductionOrder } from '../../data/mockProduccionData';
import { ProductionCard, StatusBadge } from './productionUi';

interface Props { orders: ProductionOrder[]; onOpenOrder: (order: ProductionOrder) => void; onMoveOrder: (order: ProductionOrder) => void; }
export const PlaneacionProduccion: React.FC<Props> = ({ orders, onOpenOrder, onMoveOrder }) => {
  const [area, setArea] = useState<'Todas' | ProductionArea>('Todas');
  const machines = PRODUCTION_MACHINES.filter(machine => area === 'Todas' || machine.area === area);
  const days = ['Lun 07', 'Mar 08', 'Mié 09', 'Jue 10', 'Vie 11'];
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-theme-primary" /><select value={area} onChange={event => setArea(event.target.value as 'Todas' | ProductionArea)} className="rounded-xl border border-theme-subtle bg-theme-surface p-2 text-xs"><option>Todas</option><option>Offset</option><option>Flexografía</option><option>Acabados</option></select><span className="text-xs text-theme-muted">Semana 37 · capacidad y paginación demo</span></div><span className="text-xs text-theme-muted"><AlertTriangle className="mr-1 inline h-3.5 w-3.5 text-amber-600" />Borde rojo = reserva pendiente</span></div><ProductionCard><div className="overflow-x-auto"><div className="min-w-[1060px]"><div className="grid grid-cols-[230px_repeat(5,1fr)] border-b border-theme-subtle text-[10px] font-bold uppercase text-theme-muted"><span className="p-3">Máquina / capacidad</span>{days.map(day => <span className="p-3 text-center" key={day}>{day}</span>)}</div>{machines.map((machine, row) => { const machineOrders = orders.filter(order => order.machine === machine.name); const order = machineOrders[0]; return <div className="grid grid-cols-[230px_repeat(5,1fr)] border-b border-theme-subtle text-xs" key={machine.id}><span className="p-3"><b>{machine.name}</b><small className="mt-1 block text-theme-muted">{machine.area} · {machine.load}% carga · {machine.status}</small></span>{days.map((day, column) => <div className="min-h-20 border-l border-theme-subtle p-2" key={day}>{order && column === row % days.length && <div className={`rounded-xl border p-2 ${order.materialAlert ? 'border-rose-400' : 'border-theme-primary/40'} bg-theme-surface`}><button onClick={() => onOpenOrder(order)} className="w-full text-left"><b className="font-mono text-[10px]">{order.folio}</b><small className="mt-1 block text-theme-muted">{order.cliente} · {order.progress}%</small></button><div className="mt-2 flex items-center justify-between"><StatusBadge status={order.status} /><button onClick={() => onMoveOrder(order)} className="inline-flex items-center text-[10px] font-bold text-theme-primary">Mover <ChevronRight className="h-3 w-3" /></button></div></div>}</div>)}</div>; })}</div></div></ProductionCard></div>;
};
