import React, { useMemo, useState } from 'react';
import { Plus } from 'lucide-react';
import { PRODUCTION_ORDERS, ProductionOrder } from '../../data/mockProduccionData';
import { DashboardProduccion } from './DashboardProduccion';
import { PlaneacionProduccion } from './PlaneacionProduccion';
import { OrdenesProduccion } from './OrdenesProduccion';
import { OrdenProduccionDetail } from './OrdenProduccionDetail';
import { PisoProduccion } from './PisoProduccion';
import { MaquinasCapacidad } from './MaquinasCapacidad';
import { AnaliticaProduccion } from './AnaliticaProduccion';
import { ReportarIncidenciaModal } from './ReportarIncidenciaModal';

type ProductionTab = 'Dashboard' | 'Planeación' | 'Órdenes' | 'Piso' | 'Máquinas' | 'Analítica';
export const ProduccionPage: React.FC = () => {
  const [tab, setTab] = useState<ProductionTab>('Dashboard'); const [orders, setOrders] = useState<ProductionOrder[]>(PRODUCTION_ORDERS); const [selected, setSelected] = useState<ProductionOrder | null>(null); const [incidence, setIncidence] = useState<ProductionOrder | null>(null); const [notice, setNotice] = useState('');
  const activeOrders = useMemo(() => orders.filter(order => !['Terminada', 'Liberada'].includes(order.status)), [orders]);
  const updateOrder = (id: string, patch: Partial<ProductionOrder>) => setOrders(current => current.map(order => order.id === id ? { ...order, ...patch } : order));
  const openOrder = (order: ProductionOrder) => setSelected(orders.find(item => item.id === order.id) ?? order);
  const saveIncident = (minutes: number, category: string, comment: string) => { if (!incidence) return; updateOrder(incidence.id, { status: 'Detenida', stopMinutes: (incidence.stopMinutes ?? 0) + minutes }); setNotice(`Incidencia ${category} registrada en ${incidence.folio}${comment ? ` · ${comment}` : ''}. ${minutes} min reflejados en el piso.`); setIncidence(null); };
  const releaseOrder = () => { if (!selected) return; updateOrder(selected.id, { status: 'Liberada', progress: 100 }); setNotice(`${selected.folio} liberada por Calidad y disponible para producto terminado.`); setSelected(null); };
  return <div className="space-y-5 animate-in fade-in duration-200"><div className="flex flex-col gap-3 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-black tracking-widest text-theme-primary">PRODUCCIÓN · RTM</p><h1 className="text-2xl font-black text-theme-main">Producción y piso</h1><p className="text-xs text-theme-muted">Del pedido a la liberación: planeación, insumos, ejecución y trazabilidad.</p></div><button onClick={() => setNotice('Nueva OP demo preparada desde Pedido; valida stock PT, materiales y capacidad antes de programar.')} className="w-fit rounded-xl bg-theme-primary px-3 py-2 text-xs font-bold text-white"><Plus className="mr-1 inline h-4 w-4" />Nueva OP</button></div><div className="flex gap-1 overflow-x-auto border-b border-theme-subtle">{(['Dashboard', 'Planeación', 'Órdenes', 'Piso', 'Máquinas', 'Analítica'] as ProductionTab[]).map(item => <button onClick={() => setTab(item)} key={item} className={`shrink-0 border-b-2 px-4 py-3 text-xs font-bold ${tab === item ? 'border-theme-primary text-theme-primary' : 'border-transparent text-theme-muted'}`}>{item}</button>)}</div>{notice && <div className="flex items-center justify-between gap-4 rounded-xl border border-emerald-400 bg-theme-surface p-3 text-xs"><span>{notice}</span><button onClick={() => setNotice('')} className="font-bold text-emerald-700">Cerrar</button></div>}{tab === 'Dashboard' && <DashboardProduccion orders={orders} onOpenOrder={openOrder} />}{tab === 'Planeación' && <PlaneacionProduccion orders={orders} onOpenOrder={openOrder} onMoveOrder={order => { updateOrder(order.id, { due: '12 Sep' }); setNotice(`${order.folio} reprogramada visualmente a 12 Sep; capacidad de ${order.machine} actualizada.`); }} />}{tab === 'Órdenes' && <OrdenesProduccion orders={orders} onOpenOrder={openOrder} />}{tab === 'Piso' && <PisoProduccion orders={activeOrders} onOpenOrder={openOrder} onUpdate={updateOrder} onIncident={setIncidence} />}{tab === 'Máquinas' && <MaquinasCapacidad />}{tab === 'Analítica' && <AnaliticaProduccion orders={orders} onNotice={setNotice} />}{selected && <OrdenProduccionDetail order={orders.find(order => order.id === selected.id) ?? selected} onClose={() => setSelected(null)} onIncident={() => { setIncidence(selected); setSelected(null); }} onRelease={releaseOrder} />}{incidence && <ReportarIncidenciaModal order={incidence} onClose={() => setIncidence(null)} onSave={saveIncident} />}</div>;
};
