import React, { useState } from 'react';
import { X } from 'lucide-react';
import { ProductionOrder } from '../../data/mockProduccionData';
import { ModalPortal } from '../common/ModalPortal';

interface Props { order: ProductionOrder; onClose: () => void; onSave: (minutes: number, category: string, comment: string) => void; }
export const ReportarIncidenciaModal: React.FC<Props> = ({ order, onClose, onSave }) => {
  const [category, setCategory] = useState('Máquina'); const [minutes, setMinutes] = useState('30'); const [comment, setComment] = useState('');
  return <ModalPortal onClose={onClose}><div className="w-full max-w-lg rounded-3xl bg-theme-surface p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-[10px] font-black tracking-widest text-theme-primary">INCIDENCIA 4M · PISO</p><h2 className="font-black text-theme-main">{order.folio}</h2><p className="text-xs text-theme-muted">{order.machine} · {order.operator}</p></div><button onClick={onClose} aria-label="Cerrar"><X /></button></div><div className="mt-5 grid gap-3 text-xs"><label>Categoría<select value={category} onChange={event => setCategory(event.target.value)} className="mt-1 block w-full rounded-xl border border-theme-subtle bg-theme-surface p-3">{['Máquina', 'Material', 'Mano de obra', 'Método'].map(item => <option key={item}>{item}</option>)}</select></label><label>Tipo / comentario<input value={comment} onChange={event => setComment(event.target.value)} placeholder="Ej. ajuste de registro" className="mt-1 block w-full rounded-xl border border-theme-subtle p-3" /></label><div className="grid grid-cols-2 gap-3"><label>Inicio<input defaultValue="10:15" className="mt-1 block w-full rounded-xl border border-theme-subtle p-3" /></label><label>Minutos perdidos<input value={minutes} onChange={event => setMinutes(event.target.value)} type="number" className="mt-1 block w-full rounded-xl border border-theme-subtle p-3" /></label></div><label className="flex items-center gap-2"><input type="checkbox" defaultChecked /> Detener tiempo productivo</label></div><button onClick={() => onSave(Number(minutes) || 0, category, comment)} className="mt-5 w-full rounded-xl bg-theme-primary p-3 text-xs font-bold text-white">Registrar incidencia {category}</button></div></ModalPortal>;
};
